//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormGraphLIA
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodSales
    {
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string Category { get; set; }
        public string Product { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public int id { get; set; }
    }
}
